version: "3.9"
services:
    #Microsservice
    server:
        container_name: backend
        build: .
        environment:
            db_internal_url: "jdbc:postgresql://postgres:5432/postgres"
            db_user: "user"
            db_password: "password"
        ports:
            - "10000:10000"

    #Postgres        
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "password"
        ports:
            - "10001:5432"