server:
  port: 10000

spring:
  devtools:
    livereload:
      enabled: false
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      url: ${db_internal_url}
      username: ${db_user}
      password: ${db_password}
  database:
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        show-sql: false